/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ec.edu.espol.workshops;


/**
* Javadoc. Premium computation method
*/
public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
