/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package ec.edu.espol.workshops;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Assertions;

class LibraryTest {
  

 
  //TEST: FUNCTIONAL SYSTEM TEST
  @Test void computePremiumTest() {
	  CarInsurance myInsurance = new CarInsurance();
	  
	  myInsurance.setAll(17, 'M', true);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C01
	  myInsurance.setAll(17, 'M', false);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(17, 'M', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(17, 'F', true);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C01
	  myInsurance.setAll(17, 'F', false);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(17, 'F', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(17, 'A', true);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C01
	  myInsurance.setAll(17, 'A', false);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(17, 'A', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  
	  myInsurance.setAll(24, 'M', true);
	  Assertions.assertEquals(myInsurance.computePremium(),300);//CASE-ID: T004-C01
	  myInsurance.setAll(24, 'M', false);
	  Assertions.assertEquals(myInsurance.computePremium(),2000);//CASE-ID: T004-C02
	  myInsurance.setAll(24, 'M', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(24, 'F', true);
	  Assertions.assertEquals(myInsurance.computePremium(),300);//CASE-ID: T004-C01
	  myInsurance.setAll(24, 'F', false);
	  Assertions.assertEquals(myInsurance.computePremium(),300);//CASE-ID: T004-C02
	  myInsurance.setAll(24, 'F', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(24, 'A', true);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C01
	  myInsurance.setAll(24, 'A', false);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(24, 'A', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  
	  myInsurance.setAll(81, 'M', true);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C01
	  myInsurance.setAll(81, 'M', false);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(81, 'M', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(81, 'F', true);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C01
	  myInsurance.setAll(81, 'F', false);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(81, 'F', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(81, 'A', true);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C01
	  myInsurance.setAll(81, 'A', false);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  myInsurance.setAll(81, 'A', null);
	  Assertions.assertEquals(myInsurance.computePremium(),-1);//CASE-ID: T004-C02
	  
  }
  
  
}
